repos:
  - repo: https://github.com/prettier/prettier
    rev: '1.16.4'
    hooks:
      - id: prettier
        args: [config ./.prettierrc]
  - repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3
